name: Deploy CloudFormation Stack
description: Deploy CloudFormation S3 Bucket Stack

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - 'templates/**'
      - .github/workflows/ci.yaml


permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  deploy-s3-bucket-stack:
    uses: subhamay-bhattacharyya-gha/cloudformation-deploy-wf/.github/workflows/cfn-deploy.yaml@v1.1.0
    secrets: inherit
    with:
      environment: devl
      aws-region: ${{ vars.AWS_REGION }}
      aws-account-id: "270453428528"
      oidc-role-name: ${{ vars.AWS_OIDC_ROLE}}
      cfn-templates-s3-bucket: subhamay-cfn-nested-templates-270453428528-devl-us-east-1
      stack-name: s3-bucket-stack
      template-file: templates/s3-bucket.yaml
      parameters-file: templates/parameters.json