name: Deploy CloudFormation Stack

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - 'templates/**'
      - .github/workflows/ci.yaml

env:
  ENVIRONMENT: devl
  OIDC_ROLE_NAME: ${{ vars.OIDC_ROLE_NAME  }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  CFN_TEMPLATES_S3_BUCKET: ${{ vars.CFN_TEMPLATES_S3_BUCKET }}
  S3_BUCKET_STACK_NAME: s3-bucket-stack
  S3_BUCKET_POLICY_STACK_NAME: s3-bucket-policy-stack

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  config:
    name: Get Environment Configuration
    runs-on: ubuntu-latest
    environment: devl
    outputs:
      environment: ${{ steps.config.outputs.environment }}
      aws-region: ${{ steps.config.outputs.aws-region }}
      aws-account-id: ${{ steps.config.outputs.aws-account-id }}
      oidc-role-name: ${{ steps.config.outputs.oidc-role-name }}
      cfn-templates-s3-bucket: ${{ steps.config.outputs.cfn-templates-s3-bucket }}
      cfn-s3-bucket-stack: ${{ steps.config.outputs.cfn-s3-bucket-stack }}
      cfn-s3-bucket-policy-stack: ${{ steps.config.outputs.cfn-s3-bucket-policy-stack }}
    steps:
      - id: config
        run: |
          echo "Debug: Getting environment configuration"
          echo "AWS_REGION: ${{ env.AWS_REGION }}"
          echo "AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}"
          echo "OIDC_ROLE_NAME: ${{ env.OIDC_ROLE_NAME }}"
          {
            echo "environment=${{ env.ENVIRONMENT }}"
            echo "aws-region=${{ env.AWS_REGION }}"
            echo "aws-account-id=${{ env.AWS_ACCOUNT_ID }}"
            echo "oidc-role-name=${{ env.OIDC_ROLE_NAME }}"
            echo "cfn-templates-s3-bucket=${{ env.CFN_TEMPLATES_S3_BUCKET }}"
            echo "cfn-s3-bucket-stack=${{ env.S3_BUCKET_STACK_NAME }}"
            echo "cfn-s3-bucket-policy-stack=${{ env.S3_BUCKET_POLICY_STACK_NAME }}"
          } >> "$GITHUB_OUTPUT"

  deploy:
    needs: config
    uses: subhamay-bhattacharyya-gha/cloudformation-deploy-wf/.github/workflows/cfn-deploy.yaml@bug/GHA-0008-update-github-actions-to
    with:
      environment: ${{ needs.config.outputs.environment }}
      aws-region: ${{ needs.config.outputs.aws-region }}
      aws-account-id: ${{ needs.config.outputs.aws-account-id }}
      oidc-role-name: ${{ needs.config.outputs.oidc-role-name }}
      cfn-templates-s3-bucket: ${{ needs.config.outputs.cfn-templates-s3-bucket }}
      stack-name: ${{ needs.config.outputs.cfn-s3-bucket-stack }}
      template-file: templates/s3-bucket.yaml
      parameters-file: templates/parameters.json