name: Deploy CloudFormation Stack
description: Deploy CloudFormation S3 Bucket Stack

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - 'templates/**'
      - .github/workflows/ci.yaml

env: 
  ENVIRONMENT: devl
  OIDC_ROLE_NAME: ${{ vars.OIDC_ROLE_NAME  }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  CFN_TEMPLATES_S3_BUCKET: ${{ vars.CFN_TEMPLATES_S3_BUCKET }}
  # S3_BUCKET_STACK_NAME: s3-bucket-stack
  # S3_BUCKET_POLICY_STACK_NAME: s3-bucket-policy-stack

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  deploy-s3-bucket-stack:
    # environment: devl
    # runs-on: ubuntu-latest
    uses: subhamay-bhattacharyya-gha/cloudformation-deploy-wf/.github/workflows/cfn-deploy.yaml@v1.1.0
    with:
      environment: devl
      aws-region: ${{ vars.AWS_REGION }}
      aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
      oidc-role-name: ${{ vars.OIDC_ROLE_NAME }}
      cfn-templates-s3-bucket: ${{ vars.CFN_TEMPLATES_S3_BUCKET }}
      stack-name: s3-bucket-stack
      template-file: templates/s3-bucket.yaml
      parameters-file: templates/parameters.json